spring:
  application:
    name: dzoj-backend-question-service
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    store-type: redis
    # 30
    timeout: 2592000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.91.249.196:3306/oj
    username: root
    password: dazhou520
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    timeout: 5000
  servlet:
    multipart:
      max-file-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    password: guest
    username: guest
    # 启动publisher-confirm，这里支持两种类型
    #correlated：异步回调，定义 ConfirmCallback，MQ 返回结果时会回调这个 ConfirmCallback
    publisher-confirm-type: correlated
    # 开启 publish-return 功能，同样是基于 callback 机制，不过是定义 ReturnCallback
    publisher-returns: true
    # 定义消息路由失败时的策略。true，则调用 ReturnCallback；false：则直接丢弃消息
    template:
      mandatory: true
server:
  address: 0.0.0.0
  port: 8103
  servlet:
    context-path: /api/question
    # cookie 30
    session:
      cookie:
        max-age: 2592000
        path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
# 沙箱
codesandbox:
  type: remote
knife4j:
  enable: true