spring:
  application:
    name: dzoj-backend-question-service
  # \u9ED8\u8BA4 dev \u73AF\u5883
  profiles:
    active: dev
  # \u652F\u6301 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session \u914D\u7F6E
  session:
    store-type: redis
    # 30 \u5929\u8FC7\u671F
    timeout: 2592000
  # \u6570\u636E\u5E93\u914D\u7F6E
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oj?useSSL=FALSE&serverTimezone=UTC
    username: root
    password: dazhou520
  # Redis \u914D\u7F6E
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
  servlet:
    multipart:
      # \u5927\u5C0F\u9650\u5236
      max-file-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
    # 启动publisher-confirm，这里支持两种类型
    #correlated：异步回调，定义 ConfirmCallback，MQ 返回结果时会回调这个 ConfirmCallback
    publisher-confirm-type: correlated
    # 开启 publish-return 功能，同样是基于 callback 机制，不过是定义 ReturnCallback
    publisher-returns: true
    # 定义消息路由失败时的策略。true，则调用 ReturnCallback；false：则直接丢弃消息
    template:
      mandatory: true
server:
  address: 0.0.0.0
  port: 8103
  servlet:
    context-path: /api/question
    # cookie 30 \u5929\u8FC7\u671F
    session:
      cookie:
        max-age: 2592000
        path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # \u5168\u5C40\u903B\u8F91\u5220\u9664\u7684\u5B9E\u4F53\u5B57\u6BB5\u540D
      logic-delete-value: 1 # \u903B\u8F91\u5DF2\u5220\u9664\u503C\uFF08\u9ED8\u8BA4\u4E3A 1\uFF09
      logic-not-delete-value: 0 # \u903B\u8F91\u672A\u5220\u9664\u503C\uFF08\u9ED8\u8BA4\u4E3A 0\uFF09
# \u4EE3\u7801\u6C99\u7BB1\u914D\u7F6E
codesandbox:
  type: remote
knife4j:
  enable: true